//! Core rule set — marker-gated project outputs plus known `$HOME` cache
//! roots. Domain-specific rules live in sibling modules.

use std::path::Path;

use crate::model::{Category, Severity};

use super::{match_home_rule, parent_has_file, parent_has_py, HomeRule, Match};

/// True if any direct child of `parent` is a `.tf` Terraform file.
fn parent_contains_tf(parent: &Path) -> bool {
    let Ok(rd) = std::fs::read_dir(parent) else {
        return false;
    };
    rd.filter_map(|e| e.ok())
        .any(|e| e.path().extension().is_some_and(|ext| ext == "tf"))
}

/// Path fragments that mark a tree as SHIPPED WITH AN APPLICATION rather
/// than built by the user. A `node_modules` in here is not restorable by
/// `npm install` — there is no install step — and deleting it breaks the
/// application. `~/.vscode/extensions` alone accounted for 658 MiB of
/// findings whose note promised a recovery that does not exist.
const VENDOR_TREES: &[&str] = &[
    "/.vscode/extensions/",
    "/.vscode-server/extensions/",
    "/.vscode-oss/extensions/",
    "/.cursor/extensions/",
    "/lib/node_modules/",
    "/usr/share/",
    "/usr/lib/",
    "/opt/",
];

fn in_vendor_tree(dir: &Path) -> bool {
    let text = dir.to_string_lossy().replace('\\', "/");
    VENDOR_TREES.iter().any(|frag| text.contains(frag))
}

/// True if `dir` sits underneath a `node_modules` directory. Dependencies
/// ship their own `dist/`, so without this every dependency of an unmatched
/// `node_modules` became its own finding.
fn inside_node_modules(dir: &Path) -> bool {
    dir.parent().is_some_and(|p| {
        p.components()
            .filter_map(|c| c.as_os_str().to_str())
            .any(|c| c == "node_modules")
    })
}

/// Lockfiles proving a `node_modules` was produced by an install the user
/// can repeat. A bare `package.json` is not enough: every vendored
/// application tree has one.
const JS_LOCKFILES: &[&str] = &[
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "npm-shrinkwrap.json",
    "bun.lockb",
];

/// Evaluate the core rule set against `dir`.
pub(crate) fn classify(dir: &Path) -> Option<Match> {
    marker_rule(dir).or_else(|| match_home_rule(dir, HOME_RULES))
}

fn marker_rule(dir: &Path) -> Option<Match> {
    let name = dir.file_name()?.to_str()?;
    let parent = dir.parent()?;
    if inside_node_modules(dir) || in_vendor_tree(dir) {
        return None;
    }
    let (cat, sev) = (Category::BuildArtifacts, Severity::Moderate);
    let m = |note: String| {
        Some(Match {
            category: cat,
            severity: sev,
            note,
        })
    };
    match name {
        "node_modules" if parent_has_file(parent, JS_LOCKFILES) => {
            m("npm packages — restored by `npm install`".into())
        }
        "target" if parent_has_file(parent, &["Cargo.toml"]) => {
            m("Rust build output — rebuilt by `cargo build`".into())
        }
        ".next" | ".nuxt" if parent_has_file(parent, &["package.json"]) => {
            m("framework build output — regenerated by dev/build".into())
        }
        // Flutter/Dart writes compiled output (APKs, intermediates, web
        // bundles) to `<project>/build`; `pubspec.yaml` beside it is the
        // Dart-specific marker. `flutter build` regenerates the whole tree.
        "build" if parent_has_file(parent, &["pubspec.yaml"]) => {
            m("Flutter/Dart build output — regenerated by the next flutter build".into())
        }
        // `Cargo.toml` deliberately absent: cargo writes to `target`, never
        // to `build`/`dist`. CMake/Ninja evidence lives INSIDE the build
        // directory, which is the only reliable marker for C/C++ trees.
        "dist" | "build"
            if parent_has_file(parent, &["package.json", "pyproject.toml"])
                || parent_has_file(dir, &["CMakeCache.txt", "build.ninja"]) =>
        {
            m("build output — regenerated by the project build command".into())
        }
        ".venv" | "venv" if parent_has_file(parent, &["pyproject.toml", "requirements.txt"]) => {
            m("python virtualenv — recreated from lockfile".into())
        }
        "__pycache__" if parent_has_py(parent) => {
            m("python bytecode cache — regenerated automatically".into())
        }
        ".mypy_cache" | ".ruff_cache" | ".pytest_cache" | ".hypothesis"
            if parent_has_file(parent, &["pyproject.toml", "setup.py", "setup.cfg"])
                || parent_has_py(parent) =>
        {
            m("python tooling cache — rebuilt on the next lint/test run".into())
        }
        ".tox" | ".nox" if parent_has_file(parent, &["tox.ini", "pyproject.toml", "setup.py"]) => {
            m("test virtualenvs — recreated by the next tox/nox run".into())
        }
        ".parcel-cache" | ".turbo" if parent_has_file(parent, &["package.json"]) => {
            m("bundler/task-runner cache — rebuilt by the next dev/build".into())
        }
        "elm-stuff" if parent_has_file(parent, &["elm.json"]) => {
            m("Elm build artifacts — regenerated by the next elm make".into())
        }
        ".dart_tool" if parent_has_file(parent, &["pubspec.yaml"]) => {
            m("Dart build artifacts — recreated by the next dart/flutter command".into())
        }
        ".terraform" if parent_has_file(parent, &["main.tf"]) || parent_contains_tf(parent) => {
            m("downloaded Terraform providers/modules — re-fetched by the next init".into())
        }
        _ => None,
    }
}

const SAFE: Severity = Severity::Safe;
const MOD: Severity = Severity::Moderate;

/// `$HOME` cache roots. One table, no second copy to keep in sync.
pub(crate) const HOME_RULES: &[HomeRule] = &[
    HomeRule {
        rel: ".cache/go-build",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "Go build cache — rebuilt automatically by `go build`",
    },
    HomeRule {
        rel: "go/pkg/mod",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "Go module cache — re-fetched by `go mod download`",
    },
    HomeRule {
        rel: ".cache/gopls",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "gopls module index — rebuilt by the Go language server",
    },
    HomeRule {
        rel: ".cache/goimports",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "goimports cache — regenerated on demand",
    },
    HomeRule {
        rel: ".gradle/caches",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "Gradle caches — re-downloaded on next build",
    },
    HomeRule {
        rel: ".gradle/daemon",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "Gradle daemon logs — recreated on the next build",
    },
    HomeRule {
        rel: ".gradle/native",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "Gradle native platform binaries — re-extracted on demand",
    },
    HomeRule {
        rel: ".gradle/wrapper/dists",
        category: Category::PackageCaches,
        severity: MOD,
        note: "Gradle distributions — re-downloaded per wrapper version",
    },
    HomeRule {
        rel: ".npm/_cacache",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "npm cache — repopulated by installs",
    },
    HomeRule {
        rel: ".m2/repository",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "Maven repository — re-resolved by Maven",
    },
    HomeRule {
        rel: ".cache/pip",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "pip wheel cache — re-downloaded on install",
    },
    HomeRule {
        rel: ".pub-cache",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "Dart/Flutter package cache — restored by `pub get`",
    },
    HomeRule {
        rel: ".cache/yarn",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "Yarn cache — repopulated by the next install",
    },
    HomeRule {
        rel: ".cache/pnpm",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "pnpm cache — repopulated by the next install",
    },
    HomeRule {
        rel: ".npm/_npx",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "npx scratch installs — recreated on demand",
    },
    HomeRule {
        rel: ".local/share/pnpm/store",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "pnpm content-addressable store — restored by the next `pnpm install`",
    },
    HomeRule {
        rel: ".cache/node-gyp",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "node-gyp header downloads — refetched when a native module builds",
    },
    HomeRule {
        rel: ".node-gyp",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "node-gyp header downloads — refetched when a native module builds",
    },
    HomeRule {
        rel: ".yarn/berry/cache",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "Yarn Berry zip cache — restored by the next install",
    },
    // Was IdeToolchains/Moderate: this is a package cache cargo refetches
    // with no user action, exactly like its `.cargo/registry` sibling.
    HomeRule {
        rel: ".cargo/git",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "cargo git dependency checkouts — re-fetched on the next build",
    },
    HomeRule {
        rel: ".cargo/registry",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "crates.io registry — re-fetched by cargo",
    },
    HomeRule {
        rel: ".rustup/toolchains",
        category: Category::IdeToolchains,
        severity: MOD,
        note: "Rust toolchain installs — every build fails until `rustup toolchain install`",
    },
    HomeRule {
        rel: ".cache/pypoetry",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "Poetry download cache — refetched on demand",
    },
    HomeRule {
        rel: ".cache/pdm",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "PDM download cache — refetched on demand",
    },
    HomeRule {
        rel: ".cache/hatch",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "Hatch download cache — refetched on demand",
    },
    HomeRule {
        rel: ".cache/pre-commit",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "pre-commit hook environments — rebuilt on the next run",
    },
    HomeRule {
        rel: ".ivy2",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "Ivy cache — re-resolved from Maven repositories on the next build",
    },
    HomeRule {
        rel: ".cache/coursier",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "Coursier cache — re-resolved on the next build",
    },
    HomeRule {
        rel: ".sbt",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "sbt boot/launcher cache — re-resolved on the next build",
    },
    HomeRule {
        rel: ".hex",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "Hex.pm cache — packages re-fetched by the next mix deps.get",
    },
    HomeRule {
        rel: ".swiftpm",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "SwiftPM clone/cache data — re-fetched when a package resolves",
    },
    HomeRule {
        rel: ".gem",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "RubyGems cache — re-fetched by bundler",
    },
    HomeRule {
        rel: ".bundle/cache",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "Bundler cache — re-fetched by `bundle install`",
    },
    HomeRule {
        rel: ".cache/nix",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "Nix evaluation cache — rebuilt on demand (never the store itself)",
    },
    HomeRule {
        rel: ".cache/zig",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "Zig global build cache — rebuilt on the next compile",
    },
    HomeRule {
        rel: ".ccache",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "ccache compiler cache — rebuilt as you compile",
    },
    HomeRule {
        rel: ".cache/ccache",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "ccache compiler cache — rebuilt as you compile",
    },
    HomeRule {
        rel: ".cache/sccache",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "sccache compiler cache — rebuilt as you compile",
    },
    HomeRule {
        rel: ".cache/bazelisk",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "Bazelisk downloads — refetched on the next bazel invocation",
    },
    HomeRule {
        rel: ".cache/yay",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "AUR build cache — repopulated by the next package build",
    },
    HomeRule {
        rel: ".cache/paru",
        category: Category::PackageCaches,
        severity: SAFE,
        note: "AUR build cache — repopulated by the next package build",
    },
    HomeRule {
        rel: ".cache/electron",
        category: Category::IdeToolchains,
        severity: MOD,
        note: "downloaded Electron runtimes — re-downloaded by the next build",
    },
    HomeRule {
        rel: ".cache/electron-builder",
        category: Category::IdeToolchains,
        severity: MOD,
        note: "electron-builder tool cache — re-downloaded by the next package step",
    },
    HomeRule {
        rel: ".cache/puppeteer",
        category: Category::IdeToolchains,
        severity: MOD,
        note: "Puppeteer browser binaries — re-downloaded on install",
    },
    HomeRule {
        rel: ".cache/Cypress",
        category: Category::IdeToolchains,
        severity: MOD,
        note: "Cypress binaries — restored by `cypress install`",
    },
    HomeRule {
        rel: ".config/Code/workspaceStorage",
        category: Category::IdeToolchains,
        severity: MOD,
        note: "VS Code per-workspace state — unsaved editor layout is lost",
    },
    // Split from workspaceStorage: this is a pure V8 code cache and costs
    // nothing but a slower first launch.
    HomeRule {
        rel: ".config/Code/CachedData",
        category: Category::IdeToolchains,
        severity: SAFE,
        note: "VS Code V8 code cache — regenerated on the next launch",
    },
    HomeRule {
        rel: ".config/Code/CachedExtensionVSIXs",
        category: Category::Installers,
        severity: SAFE,
        note: "installed extension archives kept after install — safe to drop",
    },
    HomeRule {
        rel: ".ollama/models",
        category: Category::AiModels,
        severity: Severity::Risky,
        note: "AI model weights — hours to re-download, if still published",
    },
    HomeRule {
        rel: ".cache/huggingface",
        category: Category::AiModels,
        severity: Severity::Risky,
        note: "Hugging Face model cache — very large re-download",
    },
    HomeRule {
        rel: ".cache/torch",
        category: Category::AiModels,
        severity: Severity::Risky,
        note: "PyTorch hub weights — re-downloaded on next use",
    },
    HomeRule {
        rel: ".keras/models",
        category: Category::AiModels,
        severity: Severity::Risky,
        note: "Keras pretrained weights — re-downloaded on next use",
    },
    HomeRule {
        rel: ".cache/whisper",
        category: Category::AiModels,
        severity: Severity::Risky,
        note: "Whisper model weights — re-downloaded on next use",
    },
    HomeRule {
        rel: ".cache/lm-studio/models",
        category: Category::AiModels,
        severity: Severity::Risky,
        note: "LM Studio model weights — very large re-download",
    },
    HomeRule {
        rel: ".lmstudio/models",
        category: Category::AiModels,
        severity: Severity::Risky,
        note: "LM Studio model weights — very large re-download",
    },
    HomeRule {
        rel: ".cache/google-chrome",
        category: Category::BrowserSystem,
        severity: SAFE,
        note: "browser cache — regenerated during browsing",
    },
    HomeRule {
        rel: ".cache/mozilla",
        category: Category::BrowserSystem,
        severity: SAFE,
        note: "browser cache — regenerated during browsing",
    },
    HomeRule {
        rel: ".cache/thumbnails",
        category: Category::BrowserSystem,
        severity: SAFE,
        note: "thumbnail cache — regenerated when folders are browsed",
    },
    HomeRule {
        rel: ".config/google-chrome/Default/Service Worker/CacheStorage",
        category: Category::BrowserSystem,
        severity: SAFE,
        note: "Chrome service-worker cache — refilled while browsing",
    },
    HomeRule {
        rel: ".config/google-chrome/extensions_crx_cache",
        category: Category::BrowserSystem,
        severity: SAFE,
        note: "Chrome extension archive cache — refetched on demand",
    },
    HomeRule {
        rel: ".config/google-chrome/optimization_guide_model_store",
        category: Category::BrowserSystem,
        severity: SAFE,
        note: "Chrome on-device model store — re-downloaded by Chrome",
    },
];

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Category, Severity};
    use tempfile::tempdir;

    fn mk(root: &std::path::Path, rel: &str) -> std::path::PathBuf {
        let p = root.join(rel);
        std::fs::create_dir_all(&p).unwrap();
        p
    }

    // Shared crate-wide lock (rules::TEST_ENV_LOCK) serializing every
    // rule-module test that mutates CHYSTIK_TEST_HOME.
    use crate::rules::TEST_ENV_LOCK as ENV_LOCK;

    #[test]
    fn node_modules_requires_a_lockfile_not_just_package_json() {
        let root = tempdir().unwrap();
        let proj = mk(root.path(), "app");
        std::fs::write(proj.join("package.json"), "{}").unwrap();
        let nm = mk(&proj, "node_modules");
        // A bare package.json is not evidence of a repeatable install:
        // every vendored application tree ships one.
        assert!(classify(&nm).is_none(), "package.json alone must not match");

        std::fs::write(proj.join("package-lock.json"), "{}").unwrap();
        let m = classify(&nm).expect("lockfile present — should match");
        assert_eq!(m.category, Category::BuildArtifacts);
        assert_eq!(m.severity, Severity::Moderate);

        let orphan = mk(root.path(), "random/node_modules"); // no marker
        assert!(classify(&orphan).is_none());
    }

    #[test]
    fn vendored_application_trees_are_never_build_artifacts() {
        // Regression: VS Code extensions ship package.json + node_modules
        // with no install step. 658 MiB of findings promised recovery by
        // `npm install`; deleting them breaks the extension.
        let root = tempdir().unwrap();
        let ext = mk(root.path(), ".vscode/extensions/vendor.pack-1.2.3");
        std::fs::write(ext.join("package.json"), "{}").unwrap();
        std::fs::write(ext.join("package-lock.json"), "{}").unwrap();
        assert!(classify(&mk(&ext, "node_modules")).is_none());
        assert!(classify(&mk(&ext, "dist")).is_none());

        let global = mk(root.path(), "n/lib/node_modules/some-cli");
        std::fs::write(global.join("package.json"), "{}").unwrap();
        std::fs::write(global.join("package-lock.json"), "{}").unwrap();
        assert!(classify(&mk(&global, "node_modules")).is_none());
    }

    #[test]
    fn dist_inside_node_modules_is_not_its_own_finding() {
        // A dependency's own dist/ used to fragment into a separate finding
        // whenever the outer node_modules failed its marker check.
        let root = tempdir().unwrap();
        let dep = mk(root.path(), "app/node_modules/zod");
        std::fs::write(dep.join("package.json"), "{}").unwrap();
        assert!(classify(&mk(&dep, "dist")).is_none());
    }

    #[test]
    fn cmake_build_dirs_match_on_their_own_evidence() {
        // Previously a C/C++ build/ matched only if the project happened to
        // ship a pyproject.toml, and missed otherwise.
        let root = tempdir().unwrap();
        let proj = mk(root.path(), "native");
        let build = mk(&proj, "build");
        assert!(classify(&build).is_none(), "no build evidence yet");
        std::fs::write(build.join("CMakeCache.txt"), "").unwrap();
        assert_eq!(
            classify(&build).expect("CMake build dir").category,
            Category::BuildArtifacts
        );
    }

    #[test]
    fn rust_target_needs_cargo_toml() {
        let root = tempdir().unwrap();
        let proj = mk(root.path(), "svc");
        std::fs::write(proj.join("Cargo.toml"), "[package]").unwrap();
        let m = classify(&mk(&proj, "target")).expect("match");
        assert_eq!(m.category, Category::BuildArtifacts);
    }

    #[test]
    fn python_venv_and_pycache() {
        let root = tempdir().unwrap();
        let proj = mk(root.path(), "pyproj");
        std::fs::write(proj.join("requirements.txt"), "").unwrap();
        assert!(classify(&mk(&proj, ".venv")).is_some());
        std::fs::write(proj.join("main.py"), "print(1)").unwrap();
        assert!(classify(&mk(&proj, "__pycache__")).is_some());
    }

    #[test]
    fn home_caches_are_safe_package_category() {
        let _env = ENV_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        // Uses real $HOME prefix logic against a fake HOME env var.
        let fake = tempdir().unwrap();
        std::env::set_var("CHYSTIK_TEST_HOME", fake.path());
        let gb = mk(fake.path(), ".cache/go-build");
        let m = classify(&gb).expect("match");
        assert_eq!(m.category, Category::PackageCaches);
        assert_eq!(m.severity, Severity::Safe);

        let models = mk(fake.path(), ".ollama/models");
        let m = classify(&models).expect("match");
        assert_eq!(m.category, Category::AiModels);
        assert_eq!(m.severity, Severity::Risky);
        std::env::remove_var("CHYSTIK_TEST_HOME");
    }

    #[test]
    fn gradle_wrapper_is_moderate_but_caches_safe() {
        let _env = ENV_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let fake = tempdir().unwrap();
        std::env::set_var("CHYSTIK_TEST_HOME", fake.path());
        assert_eq!(
            classify(&mk(fake.path(), ".gradle/caches"))
                .unwrap()
                .severity,
            Severity::Safe
        );
        assert_eq!(
            classify(&mk(fake.path(), ".gradle/wrapper/dists"))
                .unwrap()
                .severity,
            Severity::Moderate
        );
        std::env::remove_var("CHYSTIK_TEST_HOME");
    }

    #[test]
    fn plain_directory_does_not_match() {
        let root = tempdir().unwrap();
        assert!(classify(&mk(root.path(), "src")).is_none());
    }

    #[test]
    fn python_tooling_caches_are_marker_gated() {
        let root = tempdir().unwrap();
        let proj = mk(root.path(), "py");
        std::fs::write(proj.join("pyproject.toml"), "").unwrap();
        for name in [".mypy_cache", ".ruff_cache", ".pytest_cache"] {
            assert!(classify(&mk(&proj, name)).is_some(), "{name}");
        }
        // Without a python marker the same names stay unclassified.
        let bare = mk(root.path(), "rust-proj");
        assert!(classify(&mk(&bare, ".mypy_cache")).is_none());
    }

    #[test]
    fn tox_parcel_turbo_elm_dart_terraform_markers() {
        let root = tempdir().unwrap();
        let tox = mk(root.path(), "toxproj");
        std::fs::write(tox.join("tox.ini"), "").unwrap();
        assert!(classify(&mk(&tox, ".tox")).is_some());

        let js = mk(root.path(), "jsapp");
        std::fs::write(js.join("package.json"), "{}").unwrap();
        assert!(classify(&mk(&js, ".parcel-cache")).is_some());
        assert!(classify(&mk(&js, ".turbo")).is_some());

        let elm = mk(root.path(), "elmapp");
        std::fs::write(elm.join("elm.json"), "{}").unwrap();
        assert!(classify(&mk(&elm, "elm-stuff")).is_some());

        let dart = mk(root.path(), "dartapp");
        std::fs::write(dart.join("pubspec.yaml"), "").unwrap();
        assert!(classify(&mk(&dart, ".dart_tool")).is_some());

        let tf = mk(root.path(), "infra");
        std::fs::write(tf.join("main.tf"), "").unwrap();
        assert!(classify(&mk(&tf, ".terraform")).is_some());
    }

    #[test]
    fn node_rust_scala_home_caches_match() {
        let _env = ENV_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let fake = tempdir().unwrap();
        std::env::set_var("CHYSTIK_TEST_HOME", fake.path());
        for rel in [
            ".cache/yarn",
            ".cache/pnpm",
            ".local/share/pnpm/store",
            ".npm/_npx",
            ".cache/pypoetry",
            ".cache/pdm",
            ".cache/hatch",
            ".ivy2",
            ".cache/coursier",
            ".sbt",
            ".hex",
            ".swiftpm",
        ] {
            let m = classify(&mk(fake.path(), rel)).expect(rel);
            assert_eq!(m.category, Category::PackageCaches, "{rel}");
            assert_eq!(m.severity, Severity::Safe, "{rel}");
        }
        // `.cargo/git` is a package cache cargo refetches with no user
        // action — same contract as its `.cargo/registry` sibling.
        let cargo_git = classify(&mk(fake.path(), ".cargo/git")).expect("cargo git");
        assert_eq!(cargo_git.category, Category::PackageCaches);
        assert_eq!(cargo_git.severity, Severity::Safe);
        let rustup = classify(&mk(fake.path(), ".rustup/toolchains")).expect("rustup");
        assert_eq!(rustup.category, Category::IdeToolchains);
        assert_eq!(rustup.severity, Severity::Moderate);
        // Negatives: installed cargo bins and rustup settings are not targets.
        assert!(classify(&mk(fake.path(), ".cargo/bin")).is_none());
        assert!(classify(&mk(fake.path(), ".rustup/settings.toml")).is_none());
        std::env::remove_var("CHYSTIK_TEST_HOME");
    }
}
