//! Generic system junk in `$HOME`: app crash dumps, stale core files,
//! orphaned X11/Wayland session leftovers, one-off `.cache` strays.

use std::path::Path;

use crate::model::{Category, Severity};

use super::{home_root, Match};

/// Evaluate the system-junk rule set against `dir`.
pub(crate) fn classify(dir: &Path) -> Option<Match> {
    home_rule(dir)
}
/// Desktop-generic regenerables: driver/GPU shader caches, font and icon
/// caches, shell caches, desktop-search indexes and crash dumps.
/// `.cache/thumbnails` is claimed by core.rs; bare `.cache` never matches.
const HOME_TARGETS: &[(&str, Severity, &str)] = &[
    (
        ".cache/mesa_shader_cache",
        Severity::Safe,
        "Mesa GPU shader cache — rebuilt by the graphics driver",
    ),
    (
        ".cache/mesa_shader_cache_db",
        Severity::Safe,
        "Mesa GPU shader cache (new format) — rebuilt by the graphics driver",
    ),
    (
        ".cache/nvidia/GLCache",
        Severity::Safe,
        "NVIDIA OpenGL/Vulkan shader cache — rebuilt automatically",
    ),
    (
        ".cache/qtshadercache",
        Severity::Safe,
        "Qt shader cache — regenerated by Qt applications",
    ),
    (
        ".cache/fontconfig",
        Severity::Safe,
        "fontconfig cache — rebuilt from installed fonts on demand",
    ),
    (
        ".cache/gnome-shell",
        Severity::Safe,
        "GNOME Shell cache — recreated while the desktop runs",
    ),
    (
        ".cache/icon-cache.kcache",
        Severity::Safe,
        "KDE icon cache — rebuilt from the icon theme",
    ),
    (
        ".local/share/baloo",
        Severity::Moderate,
        "Baloo file-search index — fully re-indexed on the next KDE start",
    ),
    (
        ".cache/tracker3",
        Severity::Safe,
        "Tracker3 cache — regenerated by the indexer",
    ),
    (
        ".local/share/tracker3",
        Severity::Moderate,
        "Tracker3 index database — re-indexed automatically",
    ),
    (
        ".local/share/drkonqi/crashes",
        Severity::Safe,
        "KDE crash dumps — only useful for debugging past crashes",
    ),
    // The single most obvious desktop junk location, previously uncovered.
    // Moderate, not Safe: the whole point of the trash is that its contents
    // were deliberately kept recoverable.
    (
        ".local/share/Trash/files",
        Severity::Moderate,
        "files you already deleted — emptying the trash makes that permanent",
    ),
    (
        ".local/share/Trash/expunged",
        Severity::Safe,
        "partially removed trash leftovers — no longer restorable anyway",
    ),
    (
        ".cache/appstream",
        Severity::Safe,
        "AppStream metadata cache — refreshed by the software centre",
    ),
    (
        ".cache/discover",
        Severity::Safe,
        "KDE Discover cache — regenerated by the software centre",
    ),
    (
        ".cache/flatpak/system-cache",
        Severity::Safe,
        "Flatpak download staging — re-fetched on the next install",
    ),
    (
        ".local/share/systemd/coredump",
        Severity::Safe,
        "user coredumps — only useful for debugging past crashes",
    ),
    (
        ".cache/thumbnails/fail",
        Severity::Safe,
        "failed-thumbnail markers — pure garbage, retried on demand",
    ),
    (
        ".cache/winetricks",
        Severity::Safe,
        "winetricks download cache — re-fetched when a component installs",
    ),
    (
        ".cache/gstreamer-1.0",
        Severity::Safe,
        "GStreamer plugin registry cache — rebuilt on the next media playback",
    ),
];

fn home_rule(dir: &Path) -> Option<Match> {
    let home = home_root()?;
    let rel = dir
        .strip_prefix(&home)
        .ok()?
        .to_string_lossy()
        .replace('\\', "/");
    let (_, sev, note) = *HOME_TARGETS.iter().find(|(s, ..)| rel == *s)?;
    Some(Match {
        category: Category::SystemJunk,
        severity: sev,
        note: note.into(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn mk(root: &std::path::Path, rel: &str) -> std::path::PathBuf {
        std::fs::create_dir_all(root.join(rel)).unwrap();
        root.join(rel)
    }

    use crate::rules::TEST_ENV_LOCK as ENV_LOCK;

    #[test]
    fn shader_font_and_index_caches_match_with_expected_severity() {
        let _env = ENV_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let fake = tempdir().unwrap();
        std::env::set_var("CHYSTIK_TEST_HOME", fake.path());
        for rel in [
            ".cache/mesa_shader_cache",
            ".cache/mesa_shader_cache_db",
            ".cache/nvidia/GLCache",
            ".cache/qtshadercache",
            ".cache/fontconfig",
            ".cache/gnome-shell",
            ".cache/icon-cache.kcache",
            ".cache/tracker3",
            ".local/share/drkonqi/crashes",
        ] {
            let m = classify(&mk(fake.path(), rel)).expect(rel);
            assert_eq!(m.category, Category::SystemJunk, "{rel}");
            assert_eq!(m.severity, Severity::Safe, "{rel}");
        }
        let baloo = classify(&mk(fake.path(), ".local/share/baloo")).expect("baloo");
        assert_eq!(baloo.severity, Severity::Moderate);
        let tracker = classify(&mk(fake.path(), ".local/share/tracker3")).expect("tracker");
        assert_eq!(tracker.severity, Severity::Moderate);
        // Negatives: bare .cache, thumbnails (core.rs owns it), typos.
        assert!(classify(&mk(fake.path(), ".cache")).is_none());
        assert!(classify(&mk(fake.path(), ".cache/thumbnails")).is_none());
        assert!(classify(&mk(fake.path(), ".local/share/baloo4")).is_none());
        assert!(classify(&mk(fake.path(), "fontconfig")).is_none());
        std::env::remove_var("CHYSTIK_TEST_HOME");
    }

    #[test]
    fn correctly_named_tree_outside_home_does_not_match() {
        let root = tempdir().unwrap();
        assert!(classify(&mk(root.path(), "x/.cache/fontconfig")).is_none());
    }
}
